<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>arena_auditory</name>
  <version>0.0.0</version>
  <description>Arena auditory simulator: sound propagation, robot hearing, robot and human sound emission, local playback.</description>
  <maintainer email="dev@voshch.dev">voshch</maintainer>
  <license>TODO</license>

  <depend>diagnostic_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>visualization_msgs</depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>arena_people_msgs</exec_depend>
  <exec_depend>arena_robots</exec_depend>
  <exec_depend>arena_simulation_setup</exec_depend>
  <exec_depend>task_generator_msgs</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
